steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flaskapidockercloudrunbigquery/flask-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flaskapidockercloudrunbigquery/flask-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/flaskapidockercloudrunbigquery/flask-app', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated']

images:
- 'gcr.io/flaskapidockercloudrunbigquery/flask-app'

options:
  logging: CLOUD_LOGGING_ONLY