steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flaskapidockercloudrunbigquery/flask-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/$PROJECT_ID/flask-app', '--platform', 'managed', '--region', 'YOUR_REGION', '--allow-unauthenticated']

images:
- 'gcr.io/flaskapidockercloudrunbigquery/flask-app'
logsBucket: 'gs://my-build-logs'
options:
  logging: CLOUD_LOGGING_ONLY