
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Descărcăm cheia JSON din GCS în directorul de lucru al build-ului
    gsutil cp gs://cheie/flaskapidockercloudrunbigquery-88d7334afd05.json /workspace/flaskapidockercloudrunbigquery-88d7334afd05.json

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flaskapidockercloudrunbigquery/flask-app', '.']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/flaskapidockercloudrunbigquery-88d7334afd05.json'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flaskapidockercloudrunbigquery/flask-app']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/flaskapidockercloudrunbigquery-88d7334afd05.json'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/flaskapidockercloudrunbigquery/flask-app', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/flaskapidockercloudrunbigquery-88d7334afd05.json'

images:
- 'gcr.io/flaskapidockercloudrunbigquery/flask-app'

artifacts:
  objects:
    location: 'gs://cheie'
    paths: ['flaskapidockercloudrunbigquery-88d7334afd05.json']



